pulp-platform/pulp_soc

ips_list.yml
Update the FPU to the release version, including some bugfixes and documentation
=> :arrow_up: Bump FPU to v0.5.1

ips_list.yml, rtl/components/axi_slice_dc_slave_wrap.sv, rtl/fc/fc_subsystem.sv, rtl/pulp_soc/pulp_soc.sv
This fixes some issue where xcelium chokes on:
* Update RI5CY to fixed version (circumenventing parser issues in tb)
* Axi4PC doesn't exist
* zero-riscy doesn't work in the current configuration (new debug unit/interface)
* test_cgbypass_i doesn't exist in local IP
=> Fix xcelium

rtl/pulp_soc/pulp_soc.sv
This seems to cause trouble with quite a few tools. Replace with a
variable and combinatorial assignment.
=> Do not use advanced array literal

ips_list.yml
The `update-ips` script had problem with downloading the Ibex core since <https://raw.githubusercontent.com/pulp-platform/zero-riscy/pulpissimo/ips_list.yml> is no longer available.
=> Change to lowRISC upstream for Ibex

ips_list.yml, rtl/fc/fc_subsystem.sv, rtl/pulp_soc/pulp_soc.sv, rtl/pulp_soc/soc_peripherals.sv
This PR switches from Zero-riscy to Ibex. Besides switching to a newer version of the upstream IP, this also requires changes in the interrupt framework and boot address alignment. Both these changes are only conditionally enabled if Ibex is selected.
=> Switch from Zero-riscy to Ibex

rtl/pulp_soc/pulp_soc.sv, rtl/pulp_soc/soc_peripherals.sv
* `axi_to_cluster` width mismatch
* Wrong signal names for `spi` by @antmas
=> Apply synthesis fixes

rtl/pulp_soc/soc_clk_rst_gen.sv
Correct me if I'm wrong, but I believe there should be `s_rstn_cluster_sync` instead of `s_rstn_soc_sync`, which is assigned above.
=> s_rstn_cluster_sync typo fix

ips_list.yml, rtl/udma_subsystem/udma_subsystem.sv
In a concentrated effort we are merging the latest changes of our IPs (see also vega tapeout) into their respective master. Here we update the references to those new IP versions. Each commit is a bump of an IP with the appropriate shortlog appended.
=> Bump all our IPs to newest version

rtl/pulp_soc/pulp_soc.sv
This prevents synthesis. Fixes #22
=> Fix wrong ID WIDTH in soc/cluster AXI bus

ips_list.yml, rtl/fc/fc_subsystem.sv, rtl/pulp_soc/pulp_soc.sv, rtl/pulp_soc/soc_peripherals.sv
The PULPissimo-version of Ibex now supports 32 additional fast interrupts like RI5CY/CV32E40P. This allows the two cores to use the exact same interrupt framework.
=> Adapt fabric controller subsystem for updated Ibex

CHANGELOG.md, ips_list.yml, rtl/pulp_soc/boot_rom.sv
* fpnew: Bump to `v0.6.3` with divider flag fix and lint improvements
* boot_rom: Stop driving input address
=> Pulpissimo next

rtl/fc/fc_subsystem.sv, rtl/pulp_soc/pulp_soc.sv
Hi! :) 
Stemming from master, I had a patch on Zfinx for the FC core. Now is a parameter in input to the SoC and is put =1, in this way the floating point RF is neither instantiated nor used. Having Zfinx=0 causes all FP operations of executed by the FC to fail: the compiler works to support the Zfinx extension (Zfinx=1), hence it never loads any value in the fp register file but the FC doesn't know it (Zfinx=0) and fetches trash values from the FP reg file, causing FP op to fail. But I guess that no one had recently tired FP ops on the SoC. 
I tried it with the tests that you'll soon see in regression_tests and it works, along with the modifications Michael did on Pulp to bump to version 1.4.0. So, if you do not find errors, if could please merge this into master and tag as 1.4.2 that …
=> Zfinx patch on latest SoC version

rtl/components/obi_pulp_adapter.sv, src_files.yml
The module blocks multiple outstanding requests made by the processor to the memory until the first one is served.
=> Add OBI to PULP adapter

Bender.yml, ips_list.yml
This PR updates certain dependencies to reference newer versions of `tech_cells_generic`, such that no version conflicts persist across dependencies. This allows for bender to automatically resolve dependencies, without requiring an override or manual selection of a version, at least regarding `tech_cells_generic`.
This issue still persists for `axi` due to `axi_slice_dc` calling an older `axi` version. `register_interface` is updated here to avoid this issue.
=> Bump dependencies with `tech_cells_generic` compatibility

Bender.yml, ips_list.yml, rtl/components/pulp_interfaces.sv
This PR removes the definition of APB_BUS interface from the code base since it is already defined in the `apb` repository. This duplicate definition causes Spyglass to issue non-waivable fatal errors that prevent further linting of the design.
=> Remove duplicate interface APB_BUS

Bender.yml, ips_list.yml
IPApprox and Bender.yml dependency versions are out of sync. This commit fixes the issue.
=> Align bender and ipapprox dependencies

Bender.yml, CHANGELOG.md, ips_list.yml, rtl/pulp_soc/soc_interconnect.sv, rtl/pulp_soc/soc_interconnect_wrap.sv
This change reduces the pipeline stages in the AXI crossbar and axi-lite to APB peripheral. This reduces FC/uDMA to peripheral/cluster latency by 3 cycles.
=> Reduce Latency in AXI Crossbar of SoC interconnect and AXI-Lite to APB Bridge

CHANGELOG.md, rtl/pulp_soc/l2_ram_multi_bank.sv
The fpga ports no longer need out-context synthesis of the Xilinx SRAM IPs.
Instead the tech_cells_generic tc_sram wrapper will instantiate a xilinx
parametrized macro (if bender/IPapprox is given the right target). This way, we
no longer need to manually sync SRAM memory size between RTL and FPGA tcl scripts.
=> Remove explicit fpga RAM instantiation

Bender.yml, CHANGELOG.md, rtl/components/tb_fs_handler.sv, rtl/pulp_soc/pulp_soc.sv, rtl/pulp_soc/soc_peripherals.sv
This replaces the hack we have in tb_pulp where we do hierarchical
access into into pulp_soc. Now, you just have to set SIM_STDOUT to 1 to
enable simulated stdout. Will $fatal when you do this for synthesis.
=> Add simulation stdout

rtl/udma_subsystem/udma_subsystem.sv
Align `udma_subsystem` with the improved capability of an i2c master device to receive an error (`nack`) from an i2c slave device after a write:
- `nack` register is held high until further read and does not last for a clock cycle only
- `busy`, `alert` and `error` logic is wired in `udma_i2c` (it was unconnected)
- `busy` and `alert` receive the same priority of `nack`, i.e. they are kept at `1` until the nack is recognized, and an error is raised
- This branch has been tested with the pulp-runtime based [i2c master regression test](https://github.com/pulp-platform/regression_tests/tree/master/peripherals/i2c) in `pulp-open` `master` branch. Yet, the test still does not check for `nack` from a slave device; it has been executed to check against regression at the moment.
- The `ack` check …
=> Align i2c with ack/busy/alert improvements

Bender.yml, CHANGELOG.md, rtl/fc/cv32e40p_fp_wrapper.sv, rtl/fc/fc_subsystem.sv, rtl/pulp_soc/pulp_soc.sv, rtl/pulp_soc/soc_peripherals.sv, rtl/udma_subsystem/udma_subsystem.sv
* Update RI5CY to CV32E40P
* Wire up uart char and error events
* Remove ` PULP_TRAINING`  references
* Propagate ` USE_XPULP` for enabling PULP extensions
=> Update RI5CY to CV32E40P

rtl/pulp_soc/soc_interconnect.sv, rtl/pulp_soc/soc_peripherals.sv, rtl/pulp_soc/tcdm_demux.sv
Two issues cropped up when running through synopsys:
- double assigned signals (grounded `stdout_bus` in `soc_peripherals`) with `TARGET_SYNTHESIS`
- invalid symbol for array interface assignments in gen loop (See also https://github.com/pulp-platform/pulpissimo/issues/332)
=> Fixes for synthesis

rtl/pulp_soc/tcdm_error_slave.sv
The r_opc signal should come with the response signal (r_valid), a cycle after the req/gnt handshake. This change fixes a timing loop when using ibex as FC.
=> tcdm_err_slave: stall r_opc for 1 cycle

rtl/fc/fc_subsystem.sv
With the update to cv32e40p, several changes which are directly compatible with ibex were implemented. This PR aligns the implementations for the OBI adapter and interrupt vector.
=> Align ibex to cv32e40p

rtl/fc/fc_subsystem.sv, rtl/pulp_soc/pulp_soc.sv
* Update idcode
* Fix wrong ibex halt and exception address
=> Update JTAG IDCODE

rtl/fc/cv32e40p_fp_wrapper.sv
Required for synthesis with Vivado 2020.2
This is the same error as in pulp-platform/cv32e40p#2
=> Fix type of C_DIV for cv32e40p_fp_wrapper

rtl/components/tcdm_arbiter_2x1.sv
We forgot to properly set the license header for `tcdm_arbiter_2x1.sv`.
Fixes #94
=> rtl: Fix wrong license header

rtl/pulp_soc/pulp_soc.sv
`NB_HWPE_PORTS` is required for correct matching of `l2_hwpe_master`.
=> pulp_soc: Propagate NB_HWPE_PORTS to fc_subsystem
